### ISSUE TITLE
Catch PUT request

### ISSUE THREAD

**Issue by ursoforte** [kohana/core#502]
I was trying to find a way to get PUT request with Kohana.
I realized that this is already available in [L1368](https://github.com/kohana/core/blob/3.3/master/classes/Kohana/Request.php#L136)

the Controller simply:

``` php
    parse_str($this->request->body(), $put);
```

Maybe it would be interesting to have a custom method as:

``` php
$this->request->put();
```

Not that the current way of hard work.

**Comment by shadowhand** [comment]
PUT requests have an unknown body type, unless a `Content-Type` header is send with the request. In most REST APIs, a PUT request will have JSON in it, in which case `parse_str` will be useless.
