### ISSUE TITLE
Add travis-ci support for PHP 5.4+ and HHVM

### ISSUE THREAD

**Issue by enov** [kohana/core#505]
Support for PHP 5.4, 5.5, 5.6 and HHVM

**Comment by enov** [comment]
Before I update the related `.travis.yml` file, could someone confirm if we're really done with 5.3 at that point in the future (i.e. when Kohana 3.4 gets hopefully released)?

**Comment by sergeyklay** [comment]
good idea

**Comment by mintbridge** [comment]
I think if we are going to remove support for 5.3 then it should be done with a Kohana 4.0 release, it makes more sense if the 3.x series keeps 5.3 support as a lot of people will still need it

**Comment by enov** [comment]
Hey @mintbridge , thanks for your input. I understand that a lot of people will still need it.

3.4, when it hopefully sees the light, will be a _major_ release, but 3.3.x will be around for those people, until... well... 3.5 is released...

4.0 is when we do a complete rewrite... So, this is the way we number our versions...

Also, please read this:

https://groups.google.com/forum/#!msg/php-fig/ogp03OHbVJ0/_ezI_1kBlGEJ

**Comment by mintbridge** [comment]
That link doesn't seem to work for me, i'm guessing its about versioning? If we are going by semantic versioning (i dont know if we currently are @shadowhand?) then non backwards compatible changes increment the major version: http://semver.org/

Also, have we decided we doing a complete re-write? It might be worthwhile planning out what the roadmap is with community involvement before starting to make breaking changes

**Comment by enov** [comment]
Sorry about the link, I fixed it, it's a PHP FIG discussion to phase out PHP 5.3.

We did not decide a complete re-write, or anything like that. Also no major planning and such, we're trying to find out our way. But we always had BC breaking changes in major releases.

But you're right, dropping support for PHP 5.3 is a tough decision to make, so I'll defer and wait for a  core dev to decide about this.

@shadowhand , maybe you could give your final decision, if we still need to support or not PHP 5.3?

**Comment by mintbridge** [comment]
I think your're right we should be aiming to move away from 5.3, but just feel it needs to be handled in a structured way otherwise we could annoy a lot of people

**Comment by shadowhand** [comment]
PHP 5.3 is [End of Life](http://news.php.net/php.announce/99) on July 11 2014, so I don't see a reason to continue supporting it.

**Comment by zombor** [comment]
I think existing major versions need to support the php versions they originally were intended to support. If you want to drop php 5.3, a new major version should be created.

**Comment by shadowhand** [comment]
Also agree with what Jeremy is saying.

**Comment by enov** [comment]
@zombor , @shadowhand , yes, but this is for Kohana 3.4 as it is marked "milestone 3.4.0"

**Comment by zombor** [comment]
Fair enough.

**Comment by enov** [comment]
:+1: alright then, I will close this now, but updating .travis.yml is the easy part.

I will leave #504 open so that we can discuss, agree and hopefully make Travis-CI work independently for each module, also with HHVM.
