### ISSUE TITLE
Remove Direct Access Checks

### ISSUE THREAD

**Issue by lenton** [kohana/core#508]
I propose the removal of all direct access checks placed at the start of all classes:

`<?php defined('SYSPATH') OR die('No direct script access.');`

This check makes classes unusable in other non-kohana projects without first having to define 'SYSPATH'. This line of code doesn't conform to the DRY principle since it's repeated a no end of times throughout the kohana core. This removal will make classes that little more cleaner and be another step towards removing all global state.

To still prevent people from accessing class files directly; index.php (or a symbolic link) could be placed in a public folder, or a htaccess file could be used.

**Comment by shadowhand** [comment]
+1

**Comment by neo22s** [comment]
+1

**Comment by kemo** [comment]
:+1:

**Comment by mintbridge** [comment]
:thumbsup:

**Comment by samwilson** [comment]
Good idea.

**Comment by samwilson** [comment]
Will `Kohana::FILE_SECURITY` remain, and still be added to log files?

**Comment by kemo** [comment]
I'd drop it as well, log files are .php just like any other files

**Comment by sergeyklay** [comment]
Most coders this causes at least a smile.
I believe that almost any server can be configured to use a single entry point index.php.

We will not be difficult to little change a sample configuration for Apache and Nginx to prove it.
Users of other servers will be able to customize server is similar

Best regards,

**Comment by acoulton** [comment]
@lenton I think we can close this now as the PR's are merged? Reopen if not.

**Comment by pdt256** [comment]
Thanks for removing these access checks. They were unnecessary in my setup. I place my index.php inside a www directory at the same level as application, modules, etc.

Below is a sample of my Nginx config to only allow index.php to be executed. I also have a rewrite rule for module asset directories. i.e. exposing: /var/www/www.example.com/modules/mymodule/assets/img/logo.png -> http://www.example.com/assets/mymodule/img/logo.png

<pre>
    root /var/www/www.example.com/www;
    index index.php index.html;
    location ^~ /assets/ {
        root /var/www/www.example.com/modules;
        rewrite "^/assets/([a-zA-Z0-9_-]*)/(.*)$" /$1/assets/$2 break;
    }
    location / {
        try_files $uri /index.php?$query_string;
    }
        
    location = /index.php {
        include fastcgi.conf;
        fastcgi_param KOHANA_ENV production;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
    }
</pre>
