### ISSUE TITLE
$_POST is depracted

### ISSUE THREAD

**Issue by dejwid** [kohana/core#534]
$_POST is depracted but it is still used in Request class.
docs: http://php.net//manual/pl/reserved.variables.post.php
class: core/classes/kohana/Request.php

**Comment by enov** [comment]
@dejwid that's the other way round:

> 4.1.0     Introduced $_POST that deprecated $HTTP_POST_VARS.

**Comment by dejwid** [comment]
sorry, ma bad

**Comment by enov** [comment]
no worries dude, cheers!
