### ISSUE TITLE
Wrong reference for tag 3.2.3

### ISSUE THREAD

**Issue by seyfer** [kohana/core#595]
Look at 3.2.3 tag. 

From packagist
v3.2.3 reference: 3025781 2014-03-05 17:43 UTC BSD-3-Clause

But inside tag all code in kohana 3.3 naming style with first upper case letter!

Please fix, i'm can't install kohana/core for 3.2 with this error

**Comment by acoulton** [comment]
3.3.2 was accidentally released as 3.2.3 at first, ISTR. I think the only way round this is to delete the v3.2.3 tag (which points to the same commit as that for 3.3.2).

@shadowhand is that OK?
