### ISSUE TITLE
Not removed slashes (get_magic_quotes_gpc)

### ISSUE THREAD

**Issue by amberlex78** [kohana/core#601]
In  `classes/Kohana/Core.php` 

line 235: `Kohana::$magic_quotes = get_magic_quotes_gpc();`

In documentation:

`get_magic_quotes_gpc()` - Returns 0 if magic_quotes_gpc is off, 1 otherwise.

In `public static function sanitize($value)` 

line 440: `if (Kohana::$magic_quotes === TRUE)` - will not be executed

Proposal: `Kohana::$magic_quotes = (bool)get_magic_quotes_gpc();`

**Comment by enov** [comment]
Ah, my mistake:

https://github.com/kohana/core/commit/e5ce1a337706493fea09ea499b0a982e5a2f9746
