### ISSUE TITLE
Request route

### ISSUE THREAD

**Issue by saruman** [kohana/core#602]
I am not be able to get the current route using kohana.
Getting the current action, controller, directory works perfectly, but what happened to route? could you fix this?

Thank you.

Request::current()->route();

public function route(Route $route = NULL)
    {
        if ($route === NULL)
        {
            // Act as a getter
            return $this->_route;
        }
        // Act as a setter
        $this->_route = $route;
        return $this;
    }

**Comment by rjd22** [comment]
When and where are you trying to get the route? I need to know this so I can replicate it.

**Comment by saruman** [comment]
thanks for reply @rjd22.
Before sent this message, I checked again what I did and I don't know why, but now is working.
I'm sorry for the inconvenience.

Take care.

**Comment by enov** [comment]
No problem @saruman. Glad to hear it was solved!
