### ISSUE TITLE
Importing kohana-doctrine into the kohana origanisation

### ISSUE THREAD

**Issue by rjd22** [kohana/core#648]
I've been working on the following module to support Doctrine2 in the best way possible so Annotation, Yaml and XML:

https://github.com/rjd22/kohana-doctrine

I was wondering if it is a good idea to import this module into the kohana origanisation so we have a official replacement for the Kohana ORM module we no longer support. This would also help people decide what doctrine module they need to use and help focussing improvements on a single module.

@acoulton @enov @shadowhand what do you think?

**Comment by enov** [comment]
Personally, I would love to see a well maintained Doctrine module around.

But it would mean we are officially endorsing Doctrine. That might be considered opinionated, even if Doctrine is kind of de-facto nowadays. Wouldn't that backfire :fire: on us?

I looked a bit around the code and it looks good. Congrats :trophy:

**Comment by rjd22** [comment]
@enov I think it's okay to endorse Doctrine but it would not mean we are not open for other ORM's like Propel. If someone would make a module for it I would gladly include it.

But it means we won't be working on our own ORM anymore because there are better options out there and we do endorse those.

**Comment by shadowhand** [comment]
I'm in favor of Kohana adopting the package, if @rjd22 continues to maintain it. I don't feel like having a package means we endorse anything, it just provides something more official to prevent fragmentation.

:+1:

**Comment by rjd22** [comment]
@shadowhand I will continue maintaining it. Luckily @Ikke also uses it for a project.

**Comment by rjd22** [comment]
@enov @shadowhand I think it would be a good idea to change the way we do versioning starting with this package.

We used to have a <version>/develop and <version>/master branch. I think mostly for submodule support. 

Since we have releases support in github and composer I think it would make it easier to just only to have a master branch and let composer figure out what version of Kohana it will be compatible with.

I only use the config of Kohana anyway, the autoloading is done completely by composer. When you move you config file to the application folder you are able to use this module without adding it to your Kohana modules .

**Comment by enov** [comment]
@rjd22 @acoulton @shadowhand 

Besides adopting this module, we also need to add some users to the ORM module, so that they can maintain it.

**Comment by rjd22** [comment]
@enov well it depends. Do we still want to promote the usage of the ORM module or do we want to deprecate it in favor for doctrine or a different ORM library?

If the later maybe we should drop development of it.

**Comment by rjd22** [comment]
@enov @acoulton do you all agree to move the module into the kohana repository? So others can start using it?

**Comment by enov** [comment]
:+1:

**Comment by acoulton** [comment]
@rjd22 sure - we have a lighterweight version we've been using (ingenerator/kohana-doctrine2) and will probably stick with that in the immediate future as it works for us, but yours looks like a better candidate for being official.

Definitely having something so we can actively deprecate/drop kohana/orm would be good.

**Comment by rjd22** [comment]
Imported the kohana doctrine module. I will fix the composer and travis later.

**Comment by rjd22** [comment]
travis and composer fixed but I can't add it to packagist. @enov @acoulton @shadowhand do you know how to add it?

**Comment by enov** [comment]
@rjd22 You probably need additional permissions from @shadowhand

**Comment by acoulton** [comment]
If you have access to https://github.com/kohana/doctrine/settings/hooks/new?service=packagist then you should just be able to:
- Go to https://packagist.org/login and login with github - it doesn't really matter whose account is linked to the packagist project, apart from to match up the webhook API token IMHO
- Go to https://packagist.org/packages/submit and put in the repository URL
- Grab your packagist API token from https://packagist.org/profile/ 
- Set up the packagist webhook at https://github.com/kohana/doctrine/settings/hooks/new?service=packagist

If you don't have access to the kohana/doctrine settings then I guess you need to ask @shadowhand to do this, or to bump up your permissions on that repo.

Note you don't actually need permissions to add to packagist, just to set up the github webhook.

**Comment by rjd22** [comment]
I think @shadowhand needs to do it. Packagist only allows maintainers to add packages to packagist.

**Comment by shadowhand** [comment]
@rjd22 anyone can submit to packagist and you have full admin on that repo. I've also added @acoulton as an admin.

**Comment by rjd22** [comment]
@shadowhand I'm getting the following error when I'm trying to submit.

The vendor is already taken by someone else. You may ask them to add your package and give you maintainership access. The packages already in that vendor namespace can be found at kohana

**Comment by acoulton** [comment]
Hm, that's new... 

Looks like I can (I was already on as I maintainer of koharness) so I've submitted it and added you and @shadowhand as maintainers.

**Comment by shadowhand** [comment]
@acoulton thanks!

**Comment by rjd22** [comment]
Closing this since it's now finished
