### ISSUE TITLE
.git files in modules release for 3.3.5

### ISSUE THREAD

**Issue by neo22s** [kohana/core#671]
Hello!

We have in all the modules a .git file with similar content to

/modules/orm/.git:
gitdir: /home/samuel/Github/kohana/.git/modules/modules/orm

This forbids me to commit files.

**Comment by neo22s** [comment]
Not sure which milestone this should go and if its a bug or not xD what do you think @enov

**Comment by enov** [comment]
You mean, you're having problems when downloading the release zip?

**Comment by enov** [comment]
I have updated the release zip, please check.

**Comment by neo22s** [comment]
No had no issues downloading, but when adding KO to redistribute at @openclassifieds got this issue when going to commit , better just not to add the files.

If they are removed I will close it, thanks!
