### ISSUE TITLE
Ubuntu packages

### ISSUE THREAD

**Issue by neo22s** [kohana/core#673]
Hello,

I've been contacted from canonical today (Nish Aravamudan), not sure why to me maybe to some of you too?

Well going to the point they are going to remove the packages from next LTS since will use PHP7 and we are not compatible.

>  we are working on 4.0.0 which is php7 compatible.
> 
> Given that it presumably won't be released by 16.04 deadline (and we're
> already in feature freeze) I'm not sure we have a good way forward in
> 16.04, which is unfortunate since it's an LTS. But I think if there is a
> reasonable timeline we can get it into 16.10, at least? And, in the
> meanwhile, people can build from source, etc.

Are we interested to keep it there?

**Comment by rjd22** [comment]
@neo22s not sure what packages they are talking about. But if they are from Kohana I would let them remove those. People should install the new Kohana trough composer not apt-get.

update:
Most likely they are talking about these packages:
https://launchpad.net/ubuntu/+search?text=kohana

I vote remove them. They are not managed by us but by @gcsideal

**Comment by neo22s** [comment]
There were three packages in prior versions of ubuntu (I was unaware of it)

nacc@pitfall:~$ rmadison search libkohana-php
 libkohana-php | 3.1.4-1   | precise/universe | all
 libkohana-php | 3.1.5-1.1 | trusty/universe  | all
 libkohana-php | 3.1.5-1.1 | vivid/universe   | all
 libkohana-php | 3.1.5-1.1 | wily/universe    | all
 libkohana-php | 3.1.5-1.1 | xenial/universe  | all
nacc@pitfall:~$ rmadison search libkohana2-php
 libkohana2-php | 2.3.4-1 | precise/universe | source, all
 libkohana2-php | 2.3.4-2 | trusty/universe  | source, all
 libkohana2-php | 2.3.4-2 | vivid/universe   | source, all
 libkohana2-php | 2.3.4-2 | wily/universe    | source, all
nacc@pitfall:~$ rmadison search libkohana3.1-php
 libkohana3.1-php | 3.1.4-1   | precise/universe | source, all
 libkohana3.1-php | 3.1.5-1.1 | trusty/universe  | source, all
 libkohana3.1-php | 3.1.5-1.1 | vivid/universe   | source, all
 libkohana3.1-php | 3.1.5-1.1 | wily/universe    | source, all
 libkohana3.1-php | 3.1.5-1.1 | xenial/universe  | source, all
nacc@pitfall:~$ rmadison search libkohana3.2-php
 libkohana3.2-php | 3.2.0-1 | precise/universe | source, all
 libkohana3.2-php | 3.2.2-1 | trusty/universe  | source, all
 libkohana3.2-php | 3.2.2-1 | vivid/universe   | source, all
 libkohana3.2-php | 3.2.2-1 | wily/universe    | source, all
 libkohana3.2-php | 3.2.2-1 | xenial/universe  | source, all
nacc@pitfall:~$

Technically 4, but libkohana-php is a metapackage generated by
libkohana3.1-php. 

I agree they should be removed and use only composer. Just wanted to notify here.

Also not sure why still they did contact me directly from my website. Seems he did contact others but without answer.

If we all agree I will let him know. Seems the correct path to be deleted.

**Comment by rjd22** [comment]
@gcsideal do you want to keep those there?

**Comment by enov** [comment]
I think those packages should be removed. They are not updated in a timely manner (no v3.3). They might also contain security vulnerabilities.

**Comment by gcsideal** [comment]
@enov The packages are not part of the stable release, not even candidates for the next one. Those should be removed or at least updated. In two / three days I will review both paths and report back.

**Comment by enov** [comment]
@gcsideal thanks for the reply.

> The packages are not part of the stable release, not even candidates for the next one.

I did not understand this sentence, if you could kindly rephrase? Do you mean the stable _Ubuntu_ release?

**Comment by gcsideal** [comment]
@enov Sure. First, we talk (well, write) about two distinct things. _I'm not affiliated with Ubuntu_, I'm a Debian Developer. Packaged 3.1 and 3.2 for Debian. Basically we have three sets of packages in it: stable (for end users), testing (candidate for the next stable) and unstable (what we DDs use packages considered ready for further testing). I meant in my previous post that there's no Kohana package in stable nor testing. Technical users accepting that unstable occasionally breaks can install that variant of course.
The fact Ubuntu has other versions mean they packaged it as well for their distribution. I can't do anything with those packages.

**Comment by enov** [comment]
@gcsideal Thanks for clarifying.

**Comment by chrisgo** [comment]
I think we should have Ubuntu remove old packages and close this issue. Maybe we can get this added back once 4.0 gets released and compatible with PHP7
