### ISSUE TITLE
Implementation of external requests in Minion Task

### ISSUE THREAD

**Issue by entermix** [kohana/core#678]
Hello everybody! When the external request, for example:

`$request = Request::factory('http://example.com/post_api') ->method(Request::POST) ->post(array('foo' => 'bar', 'bar' => 'baz'));`

I get an error:

`Request_Exception [ 0 ]: Error fetching remote /sys/send.php [ status 0 ] Failure when receiving data from the peer ~ SYSPATH/classes/Kohana/Request/Client/Curl.php [ 102 ]`

Why is that? file_get_contents () function works without problems

**Comment by WinterSilence** [comment]
Minion_Task work in CLI, it`s not HTTP!

**Comment by knbv** [comment]
Why then runs file_get_contents and curl?

**Comment by acoulton** [comment]
@WinterSilence has misunderstood your problem. This is about **sending** HTTP requests to some other URL from a Minion_Task, not receiving them.

Unfortunately you haven't given enough information for us to help you:
- Do you have the same problem if you try to make that request from a web process (eg from a controller) or is this specific to minion?
- What is the URL you are requesting from? The error message looks like you're trying to request from `/sys/send.php` - are you providing a full absolute URL?
- Can you send a request to that URL with command-line curl and get a successful response?

Also I would strongly support @shadowhand's advice on your other ticket that Kohana's external request / curl code is not very robust and it would be much better if you used Guzzle or another library designed specifically for making HTTP requests.

**Comment by entermix** [comment]
@WinterSilence 
Why then runs file_get_contents and curl?

@acoulton

I'm trying to make an outside inquiry From inside the Mini Task

`file_get_contents('http://example.com/');`\- OK

```
    function request($url, $method = 'GET', $fields = [])
    {
        curl_setopt_array($this->_ch, [
            CURLOPT_USERAGENT => 'Example UA',
            CURLOPT_RETURNTRANSFER => TRUE,
            CURLOPT_SSL_VERIFYPEER => FALSE,
            CURLOPT_POST => ($method == 'POST'),
            CURLOPT_POSTFIELDS => $fields,
            CURLOPT_URL => $url,
        ]);

        return curl_exec($this->_ch);
    }
```

`$request = request('http://example.com/', 'GET', []);`\- OK

`$request = Request::factory('http://example.com/')->method(Request::GET)->execute()->body();` - 

`Request_Exception [ 0 ]: Error fetching remote /sys/send.php [ status 0 ] Failure when receiving data from the peer ~ SYSPATH/classes/Kohana/Request/Client/Curl.php [ 102 ]`

**Comment by acoulton** [comment]
@entermix sorry you've not answered my questions:

What happens if you use exactly the same `Request::factory()` code to send the request to the same URL from a controller action - is this minion/CLI specific or does it happen from web code as well?

What is the URL you're requesting? Is `/sys/send.php` part of the URL? If not, is that file on your system and what is it? The error message shows that's the URL curl is trying to reach - that value doesn't come from anywhere in kohana so it must be coming from your system somewhere.

**Comment by entermix** [comment]
@acoulton thank you so much! The problem was really in the URL, thanks again!
