### ISSUE TITLE
Issues with PHP 7.0.6 and ORM

### ISSUE THREAD

**Issue by neo22s** [kohana/core#687]
I am working on it but seems that since latest release of PHP 7.0.6 $model->loaded() always returns false even when its really loaded :S

Anyone else having this issue?

thanks.

**Comment by neo22s** [comment]
Seems only happens when you have a relation in the model and you do a find_all()

Simple Example 

$tickets = $users->tickets->find_all();

foreach($tickets as $ticket)
{
Here $ticket has values like id_ticket, but loaded == false
}

**Comment by Luoti** [comment]
Hello!

I don't know if these two are related, but the most recent PHP update to 5.6 branch (5.6.21) has probably also broke some ORM stuff.

https://github.com/kohana/orm/issues/129

**Comment by neo22s** [comment]
It is exactly the same, I have just reproduced it on 5.6.21 too! ok keep that one then.
