### ISSUE TITLE
ERROR: Kohana_Exception [ 0 ]: Directory APPPATH/cache must be writable

### ISSUE THREAD

**Issue by FanerK** [kohana/core#695]
Hi,

Please help me resolve this error kohana, I've tried the configuration framework still does not run.
# 

**Kohana_Exception [ 0 ]: Directory APPPATH/cache must be writable**
![screenshot from 2016-07-27 08 36 47](https://cloud.githubusercontent.com/assets/16182125/17161157/454bc598-53d5-11e6-91f6-0bb579ea0ff1.png)

**Error 1** 

_SYSPATH/classes/kohana/core.php [ 281 ]_
276             Kohana::$cache_dir = APPPATH.'cache';
277         }
278 
279         if ( ! is_writable(Kohana::$cache_dir))
280         {
281             throw new Kohana_Exception('Directory :dir must be writable',
282             array(':dir' => Debug::path(Kohana::$cache_dir)));  
283             //array(':dir' => Debug::path(Kohana::$cache_dir)));
284         }
285 
286         if (isset($settings['cache_life']))
# 

 Error 2:  
   » **Kohana_Core::init(arguments)  
     array(2) (
        "base_url" => string(14) "/var/www/html/"
        "index_file" => string(9) "index.php"
    )**
    _APPPATH/bootstrap.php [ 91 ]_

```
86     'base_url'   => '/var/www/html/',
87     'index_file' => 'index.php',
88  //'errors'   => (Kohana::$environment !== Kohana::PRODUCTION),
89  //'profile'  => (Kohana::$environment !== Kohana::PRODUCTION),
90  //'caching'  => (Kohana::$environment !== Kohana::PRODUCTION),
91 ));
92 
93 
94 /**
95  * Attach the file write to logging. Multiple writers are supported.
96  */
```
# 

  **ERROR 3** 
    »  **require(arguments)
        string(39) "/var/www/html/application/bootstrap.php"**

```
_DOCROOT/index.php [ 102 ]_ 

 97 {
 98     define('KOHANA_START_MEMORY', memory_get_usage());
 99 }
100 
101 // Bootstrap the application
102 require APPPATH.'bootstrap'.EXT;
103 
104 /**
105  * Execute the main request. A source of the URI can be passed, eg:
        $_SERVER['PATH_INFO'].
106  * If no source is specified, the URI will be automatically detected.
107  */
```

**Comment by farazmunj** [comment]
create a Directory in application Directory "cache" and make it writeable by apache.

**Comment by FanerK** [comment]
Hi farazilu,

Can you give an example to make that directory and make it writeable by apache?
I still do not understand to create a directory in question.

**Comment by farazmunj** [comment]
Hi
in application folder create a folder name "cache" and change its permissions to 777 if you are using Linux server.

**Comment by enov** [comment]
Kindly ask your support questions in the [Kohana forums](http://discourse.kohanaframework.org). Thanks!

**Comment by FanerK** [comment]
Hi enov,

This just information alone that in Kohana v3.3.6.tar.gz there is no system folder. you please check back to the url.
https://github.com/kohana/kohana/releases

**Comment by enov** [comment]
@FanerK the downloads labeled `Source code` contain only the files in `kohana/kohana` auto-generated by Github without initializing submodules. We published `kohana-v3.3.6.zip` file for your convenience. Thanks anyways for reporting.

**Comment by FanerK** [comment]
Hai enov,

I have problem associated with
✘ Kohana may not work correctly with your environment.

Please be given a solution. thank you

**Comment by enov** [comment]
Kindly ask your support questions in the [Kohana forums](http://discourse.kohanaframework.org). Thanks!
