### ISSUE TITLE
[Proposal] Make middlewares

### ISSUE THREAD

**Issue by yatsenkolesh** [kohana/core#706]
Hey, guys. What do you think about make middleware for the Kohana routes like Laravel framework ?  This is a real comfortable method to reuse code of requests filters and awesome architectural solution for make right code architecture.

**Comment by acoulton** [comment]
Hi @yatsenkolesh thanks for the suggestion. Kohana's deprecated and there's unlikely to be any active development for new features etc. You might want to discuss your idea with the community at [koseven/koseven](https://github.com/koseven/koseven) which is a fork of kohana.
